Live Submissions API integration
Judge-Girl/Judge-Girl-CMS pull request #126
Opened 2021-06-15 12:56 UTC by Wally5077

2021-06-15 13:08 UTC, nyngwang commented on src/app/exam/submissions/ExamLiveSubmissions.js
> +var examSubscriptions = {};
Is it possible to make this a Component state?

2021-06-15 13:22 UTC, nyngwang reviewed
Review done.

2021-06-15 13:22 UTC, nyngwang commented on src/app/exam/submissions/ExamLiveSubmissions.js
> +var examSubscriptions = {};
It seems like this can be removed.

2021-06-18 10:57 UTC, Johnny850807 requested changes
Review done

2021-06-18 10:57 UTC, Johnny850807 commented on src/models/VerdictIssuedEvent.js
> +    constructor({ problemId, problemTitle, studentId, studentName, submissionId, verdict, submissionTime, submissionBag }) {
remove `studentName` as it does not belong to `VerdictIssuedEvent`

2021-06-18 10:57 UTC, Johnny850807 commented on src/app/exam/submissions/ExamLiveSubmissions.js
> +    }
move the responsibility of "data completion" from the View into LiveSubmissionService (see my comment below)

2021-06-18 10:57 UTC, Johnny850807 commented on src/app/exam/submissions/ExamLiveSubmissions.js
> +                events[submissionId]["studentName"] = student.name;
`events[submissionId].studentName = student.name;`

2021-06-18 10:57 UTC, Johnny850807 commented on src/app/exam/submissions/ExamLiveSubmissions.js
> +                events[submissionId]["problemTitle"] = problem.title;
`events[submissionId].problemTitle = problem.title;`

2021-06-18 10:57 UTC, Johnny850807 commented on src/app/exam/submissions/ExamLiveSubmissions.js
> +    var events = {};
```js
const [liveSubmission, setLiveSubmissions] = useState([]) // {...LiveSubmissionEvent, verdict?, studentName, problemTitle}[]```

No need for `events`

2021-06-18 10:57 UTC, Johnny850807 commented on src/app/exam/submissions/ExamLiveSubmissions.js
> +    }
```js
function updateLiveSubmissionWithVerdict(verdictIssuedEvent) {
    const liveSubmission = liveSubmissions.find(s => s.submissionId === verdictIssuedEvent.submissionId);
    liveSubmissions = liveSubmissions.filter(s => s.submissionId !== verdictIssuedEvent.submissionId);
    setLiveSubmissions(liveSubmissions => [...liveSubmissions, liveSubmission])
}
```

2021-06-18 10:57 UTC, Johnny850807 commented on src/app/exam/submissions/ExamLiveSubmissions.js
> +
not needed

2021-06-25 13:23 UTC, Johnny850807 approved these changes
LGTM

2021-06-25 13:46 UTC, Chaoyuuu approved these changes
LGTM

2021-06-25 13:46 UTC, merged