Update exam content with illegal schedule time, show warning msg
Judge-Girl/Judge-Girl-CMS pull request #131
Opened 2021-06-21 10:09 UTC by Wally5077

![image](https://user-images.githubusercontent.com/26381900/122745585-bc9c2880-d2bb-11eb-8e31-ddc0865f2dc5.png)

2021-06-21 16:16 UTC, nyngwang requested changes
Review done! One little issue

2021-06-21 16:16 UTC, nyngwang commented on src/app/exam/options/ExamOptions.js
> +                console.log("new:", res);
Remove the testing log

2021-06-22 04:26 UTC, Johnny850807 requested changes
Review done

2021-06-22 04:26 UTC, Johnny850807 commented on src/app/exam/options/ExamSchedule.js
> +        validateTimes: validateTimes
`{  validateTimes }`

2021-06-22 04:26 UTC, Johnny850807 commented on src/app/exam/options/ExamOptions.js
> +            }).then(res => {
```js
{
                examId,
                name: newExamName,
                startTime,
                endTime,
                description: "",
            }
```

2021-06-22 04:26 UTC, Johnny850807 commented on src/app/exam/options/ExamOptions.js
>      const onButtonUpdateChangeClicked = () => {
Rename to `onButtonUpdateChangeClick` (not your change, though)

2021-06-22 04:26 UTC, Johnny850807 commented on src/app/exam/options/ExamSchedule.js
> +export default forwardRef(ExamSchedule);
Could you explain what's the need for this?

2021-06-22 07:22 UTC, Wally5077 commented on src/app/exam/options/ExamSchedule.js
> +        validateTimes: validateTimes
改成 { validateTimes } 這樣後，警告訊息沒有 work。

2021-06-22 08:27 UTC, Wally5077 commented on src/app/exam/options/ExamSchedule.js
> +export default forwardRef(ExamSchedule);
這裡的 forwardRef 是為了結合 useImperativeHandle ，讓父組件主動控制子組件的驗證時間方法

2021-06-23 09:12 UTC, Chaoyuuu approved these changes
LGTM

2021-06-23 09:12 UTC, Chaoyuuu commented on src/app/exam/options/ExamSchedule.js
> +export default forwardRef(ExamSchedule);
你可以再解釋詳細一點嗎🙏🏻   想知道＋1

2021-06-23 09:56 UTC, Johnny850807 approved these changes
LGTM

2021-06-23 14:46 UTC, nyngwang approved these changes
LGTM.

2021-06-23 15:58 UTC, merged