[Dev/124] Exam Scoreboard with Barchart
Judge-Girl/Judge-Girl-CMS pull request #132
Opened 2021-06-22 18:01 UTC by nyngwang

![image](https://user-images.githubusercontent.com/24765272/122976168-ad55d180-d3c6-11eb-899c-b18ed1e4031c.png)
![image](https://user-images.githubusercontent.com/24765272/122976209-b646a300-d3c6-11eb-807a-9143353e96de.png)

2021-06-23 08:06 UTC, Johnny850807 requested changes
1. Compose services into a new powerful one that acts as an API Gateway. Don't spread them into view files.
2. Return a powerful model class from the API Gateway to encapsulate domain knowledge (A ScoreBoard class which will compute all statistic functions for you)

2021-06-23 08:13 UTC, Johnny850807 commented on src/app/commons/Card.js
> +    color="#0B5286"
move it into exam's package, as it is uncommon

2021-06-23 08:30 UTC, Wally5077 requested changes
Review done

2021-06-23 08:30 UTC, Wally5077 commented on src/app/exam/questions/ExamQuestions.js
> +    const [editingQuestion, setEditingQuestion] = useState(null)
上面是 undefined 下面是 null，這邊是為什麼不同？

2021-06-23 08:30 UTC, Wally5077 commented on src/app/exam/questions/ExamQuestions.js
> +    const [showRejudgeQuestionModal, setShowRejudgeQuestionModal] = useState(NOT_SET)
這邊初始值為什麼是 NOT_SET 不是 false？

2021-06-23 08:30 UTC, Wally5077 commented on src/app/exam/score/ExamSummary.js
> +                <span style={{fontSize: "40px"}}>{averageScore}</span> / 100
NIT: 後面為什麼有一個 / 100？

2021-06-23 08:35 UTC, Chaoyuuu requested changes
review done

2021-06-23 08:35 UTC, Chaoyuuu commented on src/app/exam/score/ExamScore.js
> +//       Current UI design cannot handle this issue.
What did you mean?

2021-06-23 08:38 UTC, Chaoyuuu commented on src/app/exam/score/ExamSummary.js
> +                <span style={{fontSize: "40px"}}>{averageScore}</span> / 100
Total score can't be a fixed number (e.g., 100)
It should be the summation of all questions' scores.

2021-06-23 09:17 UTC, nyngwang commented on src/app/exam/live_submissions/ExamSubmissionErrors.js
> +export class UnknownVerdictSummaryError extends Error {
Will be removed XD

2021-06-23 09:24 UTC, nyngwang commented on src/app/commons/ExamRecordPreprocessing.js
> +export { recordCollector }
Will be moved to `exam/score/`

2021-06-23 09:33 UTC, nyngwang commented on src/app/exam/participants/Examinees.js
>      }
This is a bug, thanks

2021-06-24 19:50 UTC, nyngwang commented on src/app/exam/ExamList.js
> +    const [currentExaminees, setCurrentExaminees] = useState(undefined)
原本是透過`undefined`來判斷是否初始化, 如果是`[]`則`if (currentExaminees)`會為`true`.

2021-06-24 19:52 UTC, nyngwang commented on src/app/exam/participants/Examinees.js
> +            .then(() => refetchExam(examId))
原本的`removeExamineeByEmail`只是前端資料在改, 直接重新fetch就可以拿到最新資料.

2021-06-24 19:53 UTC, nyngwang commented on src/app/exam/questions/ExamQuestions.js
> +    const NOT_SET = -1
rejudge功能會用到的常數

2021-06-24 19:54 UTC, nyngwang commented on src/app/exam/questions/ExamQuestions.js
> +    const [editingQuestion, setEditingQuestion] = useState(null)
應該要是`undefined`, `null`是早期的寫法, 感謝指正.

2021-06-24 19:55 UTC, nyngwang commented on src/app/exam/questions/ExamQuestions.js
> +    const [showRejudgeQuestionModal, setShowRejudgeQuestionModal] = useState(NOT_SET)
因為`showRejudgeQuestionModal`存的值並不是`true/false`, 而是`int`, 用來表示哪個問題需要rejudge.

2021-06-24 19:56 UTC, nyngwang commented on src/app/exam/score/ExamSummary.js
> +                <span style={{fontSize: "40px"}}>{averageScore}</span> / 100
回 @Wally5077: `平均/總分`會比`平均`更有意義, 比如只顯示`100`不一定表示成績好, 因為總分可能是`1000`.

2021-06-24 19:57 UTC, nyngwang commented on src/app/exam/score/ExamSummary.js
> +                <span style={{fontSize: "40px"}}>{averageScore}</span> / 100
回 @Chaoyuuu: 已在新的檔案接上API更新.

2021-06-24 19:58 UTC, nyngwang commented on src/app/exam/score/ExamScore.js
> +//       Current UI design cannot handle this issue.
之前在line上問的UI修正, 已在新的檔案更新中移除, 感謝.

2021-06-24 20:14 UTC, nyngwang commented on src/app/exam/participants/Examinees.js
> +    const [examinees, setExaminees] = useState(undefined)
已在另一個留言回覆原因

2021-06-25 08:25 UTC, Wally5077 requested changes
Review done

2021-06-25 08:25 UTC, Wally5077 commented on src/app/exam/scoreboard/ExamScoreboardService.js
> +                    problemService.getProblemById(q.problemId).then(problem => out[q.problemId] = problem.testcases.length)))
problemService. getProblemsByIds(ids);

2021-06-25 08:25 UTC, Wally5077 commented on src/app/exam/submissions/ExamLiveSubmissions.js
> +const ExamLiveSubmissions = () => {
你這不要改名，我這邊會改

2021-06-25 08:25 UTC, Wally5077 commented on src/services/services.js
> +const examScoreService = new ExamScoreService();
const examTranscriptService = new ExamTranscriptService(examService, problemService);

2021-06-25 08:39 UTC, nyngwang commented on src/app/exam/participants/Examinees.js
> +            .then(() => refetchExam(examId))
想說用現有的`refetchExam(examId)`更新parent component, 這樣底下的相關component也會連帶更新, 就不寫多個函數做結果.一樣的事

2021-06-30 16:10 UTC, Wally5077 requested changes
Review done

2021-06-30 16:10 UTC, Wally5077 commented on src/app/exam/model.js
> +        return this.#noSubByProblemId
這檔案裡面有缺分號請一併補上

2021-06-30 16:10 UTC, Wally5077 commented on src/app/exam/scoreboard/ExamScoreboardPage.js
> +    const [presenter, setPresenter] = useState(undefined)
檔案內有缺分號的請一併補上

2021-06-30 16:10 UTC, Wally5077 commented on src/app/exam/scoreboard/ExamScoreboardPresenter.js
> +    //
刪掉這行

2021-06-30 16:10 UTC, Wally5077 commented on src/app/exam/scoreboard/ExamScoreboardPresenter.js
> +        this.#countNoSubByProblemId = examScoreboard.noSubByProblemId
檔案內檢查下分號問題

2021-06-30 16:10 UTC, Wally5077 commented on src/app/exam/scoreboard/ExamScoreboardService.js
> +            return {examinees, exam, examScores, totalTestCasesOf}
分號

2021-06-30 16:50 UTC, Wally5077 requested changes

2021-06-30 16:50 UTC, Wally5077 commented on src/services/ExamService.js
> +    }
Method name change to 'getExamTranscript'

2021-07-01 02:46 UTC, nyngwang commented on src/app/exam/scoreboard/ExamScoreboardService.js
> +                    problemService.getProblemById(q.problemId).then(problem => out[q.problemId] = problem.testcases.length)))
非常感謝你半夜趕工, 已修改!

2021-07-01 02:46 UTC, nyngwang commented on src/app/exam/model.js
> +        this.#noSubByProblemId = {}
object要先初始化才能放值

2021-07-02 11:34 UTC, Wally5077 requested changes
Review done

2021-07-02 11:34 UTC, Wally5077 commented on src/app/exam/scoreboard/ExamTranscriptService.js
> +                    .forEach(problem => totalTestCasesOf[problem.id] = problem.testcases.length))
分號

2021-07-02 11:34 UTC, Wally5077 commented on src/app/exam/scoreboard/ExamTranscriptService.js
> +            return {examinees, examOverview, examTranscript, totalTestCasesOf}
ditto

2021-07-03 05:52 UTC, Johnny850807 approved these changes
I think this can be merged first, as it's too long-live.

2021-07-03 07:28 UTC, Wally5077 requested changes
Review done

2021-07-03 07:35 UTC, Wally5077 approved these changes
LGTM

2021-07-03 13:35 UTC, timt1028 approved these changes
LGTM

2021-07-05 14:28 UTC, Chaoyuuu approved these changes
LGTM

2021-07-06 14:30 UTC, merged