Dev/118 Show warning msg when create duplicate group name
Judge-Girl/Judge-Girl-CMS pull request #142
Opened 2021-06-24 03:36 UTC by Chaoyuuu

2021-06-24 03:51 UTC, nyngwang requested changes
Review Done.

2021-06-24 03:51 UTC, nyngwang commented on src/app/group/GroupList.js
> +                                      onModalClosed={() => setShowCreateGroupModal(false)}
I think it should be `onModalClose`, based on `onSomethingClick` rather than `onSomethingClicked`.

2021-06-24 03:51 UTC, nyngwang commented on src/app/group/CreateGroupModal.js
> +const CreateGroupModal = ({show, onModalClosed, onGroupCreated}) => {
Ditto

2021-06-24 07:03 UTC, Wally5077 requested changes
Review done

2021-06-24 07:03 UTC, Wally5077 commented on src/app/group/CreateGroupModal.js
> +                onGroupCreated(group)
請補上分號

2021-06-24 07:03 UTC, Wally5077 commented on src/app/group/CreateGroupModal.js
> +        setDuplicateGroup(false)
ditto

2021-06-24 13:20 UTC, timt1028 approved these changes
LGTM

2021-06-24 14:38 UTC, Johnny850807 requested changes
Review done

2021-06-24 14:38 UTC, Johnny850807 commented on src/app/group/GroupList.js
> +                .catch(reason => console.log("group list", reason));
```js
  .catch(err => console.error("Error: ", err.getMessage()));
```

2021-06-24 14:38 UTC, Johnny850807 commented on src/app/group/CreateGroupModal.js
> +            .catch(reason => setDuplicateGroup(true));
reason -> err

2021-06-25 03:56 UTC, Johnny850807 approved these changes
LGTM

2021-06-25 06:33 UTC, nyngwang approved these changes
LGTM.

2021-06-25 07:02 UTC, Wally5077 approved these changes
LGTM

2021-06-25 07:07 UTC, merged