Dev/81 [POST]/exams/{examId}/groups
Judge-Girl/Judge-Girl-CMS pull request #143
Opened 2021-06-24 06:55 UTC by Chaoyuuu

2021-06-24 07:07 UTC, Wally5077 requested changes
Review done

2021-06-24 07:07 UTC, Wally5077 commented on src/app/exam/participants/Examinees.js
> +            fetchExaminees(examId)
請補上分號

2021-06-24 20:38 UTC, nyngwang requested changes
Review Done.

2021-06-24 20:38 UTC, nyngwang commented on src/app/exam/participants/Examinees.js
> +                               onSubmit={groupNames => addExamineesByGroups(groupNames)}/>
Can write `onSubmit={addExamineesByGroups}`.

2021-06-24 20:38 UTC, nyngwang commented on src/app/exam/participants/Examinees.js
> +                               onSubmit={emails => addExamineesByEmails(emails)}/>
ditto

2021-06-24 20:38 UTC, nyngwang commented on src/app/exam/participants/Examinees.js
> +        fetchExaminees(examId);
No need to async, just put `fetchExaminees(examId)` into `.then()`.

2021-06-25 03:55 UTC, Johnny850807 requested changes
Review done

2021-06-25 10:13 UTC, nyngwang approved these changes
LGTM

2021-06-25 13:16 UTC, Johnny850807 commented on src/app/exam/participants/Examinees.js
> +            .then(students => setExaminees(students));
rename to `examineeStudents`

2021-06-25 13:16 UTC, Johnny850807 requested changes
Review done

2021-06-25 13:53 UTC, Wally5077 approved these changes
LGTM

2021-06-25 17:49 UTC, Johnny850807 approved these changes
LGTM

2021-06-25 17:49 UTC, merged