1)Integate API [POST] /api/homework and [DELTET] /api/homework/{honew…
Judge-Girl/Judge-Girl-CMS pull request #149
Opened 2021-06-27 16:08 UTC by timt1028

resolve: #139 #138 

<img width="503" alt="截圖 2021-06-28 上午12 04 33" src="https://user-images.githubusercontent.com/69762490/123551502-a81ccc00-d7a4-11eb-8908-bfe8b5228485.png">
<img width="486" alt="截圖 2021-06-28 上午12 04 43" src="https://user-images.githubusercontent.com/69762490/123551504-aa7f2600-d7a4-11eb-9411-e45216c7f8ab.png">

2021-06-27 16:22 UTC, Johnny850807 requested changes
Review done

2021-06-27 16:22 UTC, Johnny850807 commented on src/services/HomeworkService.js
> +        const problemIds = problemList.split("\n");
problemIds should have been split as an argument

2021-06-27 16:22 UTC, Johnny850807 commented on src/app/homework/modals/CreateHomeworkModal.js
> +        homeworkService.createHomework(name, content)
content is split by '\n' here

2021-06-28 13:48 UTC, Wally5077 requested changes
Review done

2021-06-28 13:48 UTC, Wally5077 commented on src/app/homework/modals/CreateHomeworkModal.js
>      const [content, setContent] = useState();
```Js
const [content, setContent] = useState(undefined);
```

2021-06-28 13:48 UTC, Wally5077 commented on src/app/homework/modals/CreateHomeworkModal.js
> +        e.preventDefault()
e.preventDefault(); 放在第一行

2021-06-28 13:48 UTC, Wally5077 commented on src/app/homework/HomeworkList.js
>                  />
放在上一行最後

2021-06-30 16:17 UTC, Wally5077 requested changes
Review done

2021-06-30 16:17 UTC, Wally5077 commented on src/app/homework/HomeworkList.js
NIT: 這邊有多餘行數嗎？

2021-06-30 16:17 UTC, Wally5077 commented on src/app/homework/modals/CreateHomeworkModal.js
> +        e.preventDefault()
分號

2021-07-01 01:20 UTC, nyngwang requested changes
Review Done.

2021-07-01 01:20 UTC, nyngwang commented on src/app/homework/HomeworkList.js
>          return <Spinner/>
;

2021-07-01 01:20 UTC, nyngwang commented on src/app/homework/HomeworkList.js
> +    }
;

2021-07-01 01:20 UTC, nyngwang commented on src/app/homework/HomeworkList.js
>          </div>
;

2021-07-01 15:48 UTC, Johnny850807 approved these changes
LGTM

2021-07-01 15:56 UTC, timt1028 commented on src/app/homework/HomeworkList.js
>          </div>
It's the html . Not use ':'

2021-07-01 16:04 UTC, Wally5077 approved these changes
LGTM

2021-07-03 09:49 UTC, nyngwang approved these changes
LGTM.

2021-07-03 09:53 UTC, merged