archive and delete the problem
Judge-Girl/Judge-Girl-CMS pull request #151
Opened 2021-07-06 16:02 UTC by Wally5077

resolve : #109

2021-07-06 16:35 UTC, nyngwang commented on src/services/ProblemService.js
>      }
NIT: how about move `.then(...)` on the next line?

2021-07-06 16:38 UTC, nyngwang requested changes
Review Done.

2021-07-06 16:38 UTC, nyngwang commented on src/app/problem/ProblemEditor.js
> +    const [problemArchived, setProblemArchived] = useState(false);
I think `problemIsArchived`, `setProblemIsArchived` are more readable.

2021-07-07 07:04 UTC, Johnny850807 requested changes
Review done!

2021-07-07 07:04 UTC, Johnny850807 commented on src/app/problem/ProblemEditor.js
> +    const [problemArchived, setProblemArchived] = useState(false);
Improvement: `isProblemArchived`, `setIsProblemArchived`

2021-07-07 07:04 UTC, Johnny850807 commented on src/app/problem/ProblemEditor.js
> +    const RestoreAndDeleteProblemButtons = () => {
rename `RestoreOrDeleteProblemButtons`

2021-07-07 07:04 UTC, Johnny850807 commented on src/models/Problem.js
> +}
Appreciated

2021-07-07 07:11 UTC, Wally5077 commented on src/app/problem/ProblemEditor.js
> +    const RestoreAndDeleteProblemButtons = () => {
這邊是同時有兩個按鈕的關係

![image](https://user-images.githubusercontent.com/26381900/124715492-a508a500-df35-11eb-8838-753350ff3cb7.png)

2021-07-07 07:13 UTC, Johnny850807 commented on src/app/problem/ProblemEditor.js
> +    const RestoreAndDeleteProblemButtons = () => {
Make sense.

2021-07-07 07:34 UTC, Johnny850807 approved these changes
LGTM

2021-07-07 11:34 UTC, nyngwang approved these changes
LGTM.

2021-07-07 12:58 UTC, merged