[UI] Homework page #140
Judge-Girl/Judge-Girl-CMS pull request #162
Opened 2021-07-15 16:41 UTC by timt1028

#140 

<img width="1353" alt="截圖 2021-07-16 上午12 35 47" src="https://user-images.githubusercontent.com/69762490/125824898-574244ac-2d24-4799-af4b-49333acfff9f.png">
<img width="728" alt="截圖 2021-07-16 上午12 35 57" src="https://user-images.githubusercontent.com/69762490/125824915-f2d3c57a-d029-477d-ab31-7ad2bf1ed872.png">
<img width="702" alt="截圖 2021-07-16 上午12 36 05" src="https://user-images.githubusercontent.com/69762490/125824920-e0531079-246a-47dc-8513-877a4f4c334a.png">

2021-07-16 07:16 UTC, Wally5077 requested changes
Review done

2021-07-16 07:16 UTC, Wally5077 commented on src/app/homework/HomeworkPageNavigationBar.js
> +const HomeworkPageNavigationBar = function ({currentURL, homeworkName, homeworkId}) {
change to the `arrow function expression`

2021-07-16 07:16 UTC, Wally5077 commented on src/app/homework/progress/HomeworkContext.js
> +    return useContext(HomeworkContext)
;

2021-07-19 03:21 UTC, nyngwang requested changes
Review done.

2021-07-19 03:21 UTC, nyngwang commented on src/app/homework/progress/HomeworkProgressPage.js
> +                    <TextareaModal title={"Import Students"}
Remove the `{}` around `""`

2021-07-19 03:21 UTC, nyngwang commented on src/app/homework/progress/HomeworkProgressPage.js
> +                    <TextareaModal title={"Import Groups"}
ditto.

2021-07-19 09:37 UTC, Johnny850807 approved these changes
LGTM

2021-07-19 09:37 UTC, Johnny850807 commented on src/app/homework/HomeworkList.js
> +            })
semicolon

2021-07-22 07:19 UTC, Wally5077 requested changes
Review done

2021-07-22 07:19 UTC, Wally5077 commented on src/app/homework/HomeworkList.js
> +            <Redirect to={`/homework/${currentHomework.id}/homework`}/> : ""}
what's this? -> '/>'

2021-07-22 07:19 UTC, Wally5077 commented on src/app/homework/progress/HomeworkProgressPage.js
> +                            </button>
button 有不止一個 property 的話，button 的 value 換行。(Ex1)
如果只有一個的話，就維持一行。(Ex2)
Ex1:
```Js
<button className="myClassName"
        onClick={() => doSomething()}>
        value
</button>
```
Ex2:
```Js
<button className="myClassName">value</button>
```

2021-07-22 07:19 UTC, Wally5077 commented on src/app/homework/progress/HomeworkProgressPage.js
> +                    />
放在上一行最後面

2021-07-22 07:19 UTC, Wally5077 commented on src/app/homework/progress/HomeworkProgressPage.js
> +                    />
ditto

2021-07-22 07:19 UTC, Wally5077 commented on src/app/homework/progress/HomeworkProgressPage.js
> +                    />
ditto

2021-07-22 07:28 UTC, nyngwang approved these changes
LGTM.

2021-07-28 04:59 UTC, nyngwang commented on src/app/homework/HomeworkList.js
> +            <Redirect to={`/homework/${currentHomework.id}/homework`}/> : ""}
testing.

2021-09-18 12:04 UTC, Wally5077 requested changes
Review done

2021-09-18 12:04 UTC, Wally5077 commented on src/app/homework/progress/HomeworkProgressPage.js
> +                            </button>
one line

2021-09-18 12:10 UTC, Wally5077 approved these changes
LGTM

2021-09-19 03:31 UTC, merged