dev/115 Delete Exam Modal
Judge-Girl/Judge-Girl-CMS pull request #166
Opened 2021-07-22 03:56 UTC by Chaoyuuu

2021-07-22 07:24 UTC, nyngwang requested changes
Review Done.

2021-07-22 07:24 UTC, nyngwang commented on src/app/exam/options/ExamOptions.js
> +                            <TitleLine title={"Danger Zone"}/>
Remove the `{ }` pair.

2021-07-22 07:24 UTC, nyngwang commented on src/app/exam/options/ExamOptions.js
> +                                        header={'Delete this exam'}
ditto.

2021-07-22 07:24 UTC, nyngwang commented on src/app/exam/options/ExamOptions.js
> +                                        buttonName={'Delete Exam'}/>
ditto.

2021-07-22 07:24 UTC, nyngwang commented on src/app/exam/options/ExamOptions.js
> +                            <TitleLine title={"Danger Zone"}/>
Ditto.

2021-07-22 07:24 UTC, nyngwang commented on src/app/exam/options/ExamOptions.js
> +                            <TitleLine title={"Options"}/>
ditto.

2021-07-22 07:24 UTC, nyngwang commented on src/app/exam/options/ExamOptions.js
> +            {shouldRedirect ? <Redirect to={`/exams`}/> : ""}
Use `"/exams"`.

2021-07-22 07:24 UTC, nyngwang commented on src/app/exam/options/ExamOptions.js
> +                <DeleteConfirmationModal title={"Delete the Exam?"}
ditto.

2021-07-22 07:25 UTC, Wally5077 commented
Figma 上四周都是圓角，但你的似乎下方是直角
**Figma:**
![image](https://user-images.githubusercontent.com/26381900/126602995-b4410e95-eb53-4aaf-943e-527f900e1f8f.png)

**Your:**
![image](https://user-images.githubusercontent.com/26381900/126603223-91ba00e4-9e93-48ab-8cf2-fffc22cdc7c9.png)

2021-07-22 07:38 UTC, Wally5077 requested changes
Review done.

If admin does delete the exam successfully, will the exam list still show deleted exam when back to the exam list?
if the answer is 'Yes', you may need to create new issue for this.
bty, It's just my friendly reminder. 👌

2021-07-22 07:38 UTC, Wally5077 commented on src/app/exam/options/ExamOptions.js
> +        examService.deleteExam(examId).then(() => {
請把 .then 換行一下

2021-07-26 11:48 UTC, Chaoyuuu commented
> Figma 上四周都是圓角，但你的似乎下方是直角
> **Figma:**
> ![image](https://user-images.githubusercontent.com/26381900/126602995-b4410e95-eb53-4aaf-943e-527f900e1f8f.png)
> 
> **Your:**
> ![image](https://user-images.githubusercontent.com/26381900/126603223-91ba00e4-9e93-48ab-8cf2-fffc22cdc7c9.png)



> Review done.
> 
> If admin does delete the exam successfully, will the exam list still show deleted exam when back to the exam list?
> if the answer is 'Yes', you may need to create new issue for this.
> bty, It's just my friendly reminder. 👌


For the first comment about the UI modal, I have no idea why it looks different than other `DeleteConfirmationModal`. 😢  I have created an issue for this.

For the second comment, this function has already been supported in this issue :)

2021-07-26 11:55 UTC, nyngwang approved these changes
LGTM.

2021-07-26 14:58 UTC, Wally5077 approved these changes
LGTM

2021-08-14 07:11 UTC, merged