Dev/186 New Markdown Editor: Bugs in ExamQuestions.
Judge-Girl/Judge-Girl-CMS pull request #188
Opened 2021-09-11 10:56 UTC by nyngwang

Under construction. Don't review for now.

2021-09-12 10:02 UTC, Johnny850807 requested changes
Review done

2021-09-12 10:02 UTC, Johnny850807 commented on src/app/exam/options/ExamOptions.js
> +                {/* TODO: Refactor into scss. */}
do it right now

2021-09-12 10:02 UTC, Johnny850807 commented on src/app/exam/questions/ExamQuestions.js
> +            {/* TODO: refactor into scss. */}
do it right now

2021-09-18 12:43 UTC, Johnny850807 requested changes
Braces

2021-09-18 12:43 UTC, Johnny850807 commented on src/app/exam/submissions/ExamLiveSubmissions.js
> +                       .then(setExam);
braces

2021-09-18 12:43 UTC, Johnny850807 commented on src/app/exam/scoreboard/ExamScoreboardPage.js
> +    if (!exam || !presenter)
braces

2021-09-18 12:43 UTC, Johnny850807 commented on src/app/exam/scoreboard/ExamScoreboardPage.js
> +            examService.getExam(examId).then(setExam);
braces

2021-09-18 12:43 UTC, Johnny850807 commented on src/app/exam/score/ExamScorePage.js
> +            examService.getExam(examId).then(setExam);
braces

2021-09-18 12:43 UTC, Johnny850807 commented on src/app/exam/participants/Examinees.js
> +                .then(fetchExaminees);
braces

2021-09-18 12:43 UTC, Johnny850807 commented on src/app/exam/options/ExamOptions.js
> +        return <Spinner/>;
braces

2021-09-18 12:43 UTC, Johnny850807 commented on src/app/exam/options/ExamOptions.js
> +                       .then(setExam);
braces

2021-09-18 12:43 UTC, Johnny850807 commented on src/app/exam/ExamList.js
> +        return <Spinner/>;
braces

2021-09-18 12:43 UTC, Johnny850807 commented on src/app/exam/ExamInPageNavigationBar.js
> +        return <></>;
braces

2021-09-18 12:49 UTC, Wally5077 requested changes
Review done

2021-09-18 12:49 UTC, Wally5077 commented on src/app/exam/options/ExamOptions.js
> +                       .then(setExam);
setExam(exam);

2021-09-18 12:49 UTC, Wally5077 commented on src/app/exam/questions/ExamDescription.js
> +            });
put ```then``` to next line

2021-09-18 12:49 UTC, Wally5077 commented on src/app/exam/options/ExamOptions.js
> +            }).then(updateExams);
put ```then``` to next line

2021-09-18 12:49 UTC, Wally5077 commented on src/app/exam/options/ExamOptions.js
> +        examService.deleteExam(examId).then(updateExams);
put ```then``` to next line

2021-09-18 12:49 UTC, Wally5077 commented on src/app/exam/participants/Examinees.js
> +        examService.getExaminees(examId).then(setExaminees);
put ```then``` to next line

2021-09-18 12:49 UTC, Wally5077 commented on src/app/exam/participants/Examinees.js
> +        examService.addGroupsOfExaminees(examId, groupNames).then(fetchExaminees);
put ```then``` to next line

2021-09-18 12:49 UTC, Wally5077 commented on src/app/exam/participants/Examinees.js
> +        examService.deleteExaminees(examId, email).then(fetchExaminees);
put ```then``` to next line

2021-09-18 12:49 UTC, Wally5077 commented on src/app/exam/score/ExamScorePage.js
> +            examService.getExam(examId).then(setExam);
put ```then``` to next line

2021-09-18 12:49 UTC, Wally5077 commented on src/app/exam/scoreboard/ExamScoreboardPage.js
> +            examService.getExam(examId).then(setExam);
put ```then``` to next line

2021-09-18 12:49 UTC, Wally5077 commented on src/app/problem/ProblemList.js
>          problemService.getAllProblems().then(setProblems);
put ```then``` to next line

2021-09-18 12:49 UTC, Wally5077 commented on src/app/problem/editor/right/ProblemDescription.js
> +               buttonPos="top">
Your Block property 'buttonPos' has default value 'top'

2021-09-18 13:00 UTC, Johnny850807 approved these changes
LGTM

2021-09-18 13:18 UTC, Wally5077 requested changes
Review done

2021-09-18 13:18 UTC, Wally5077 commented on src/app/exam/ExamInPageNavigationBar.js
> +            examService.getExam(examId).then(setExam);
put ```then``` to next line

2021-09-18 13:46 UTC, Wally5077 approved these changes
LGTM

2021-09-18 15:14 UTC, merged