New Problem Editor: Visible / New Problem Editor: Description.
Judge-Girl/Judge-Girl-CMS pull request #191
Opened 2021-09-13 14:30 UTC by Wally5077

resolve: #173 #180

2021-09-16 06:45 UTC, Chaoyuuu requested changes
Review Done! Thanks~

2021-09-16 06:45 UTC, Chaoyuuu commented on src/app/problem/editor/right/Visible.js
>  const Visible = () => {
Please remove this TODO.

2021-09-16 06:45 UTC, Chaoyuuu commented on src/services/ProblemService.js
> +
Please rename the following methods:
`modifyProblemTitle` to `updateProblemTitle`
`modifyProblemDescription` to `updateProblemDescription`
`modifyProblemVisible` to `updateProblemVisible`

2021-09-16 06:57 UTC, Chaoyuuu approved these changes
LGTM 👍🏻

2021-09-17 09:25 UTC, Johnny850807 approved these changes
LGTM

2021-09-17 09:32 UTC, nyngwang approved these changes
LGTM.

2021-09-17 09:34 UTC, merged