Dev/164 Delete student modal
Judge-Girl/Judge-Girl-CMS pull request #192
Opened 2021-09-16 07:03 UTC by Chaoyuuu

![image](https://user-images.githubusercontent.com/41495987/133565545-6c3c516b-bbc8-46a0-993d-80c66b29f944.png)

2021-09-17 09:25 UTC, Johnny850807 approved these changes
LGTM

2021-09-24 07:48 UTC, Wally5077 approved these changes
LGTM

2021-09-25 16:51 UTC, Johnny850807 requested changes
Review done

2021-09-25 16:51 UTC, Johnny850807 commented on src/services/StudentService.js
> +        return this.axios.delete(`/api/students/${studentId}`)
semicolon

2021-09-26 09:06 UTC, Johnny850807 approved these changes
LGTM

2021-09-26 09:07 UTC, merged