Dev/177 Compilation script API integrate
Judge-Girl/Judge-Girl-CMS pull request #206
Opened 2021-09-20 17:23 UTC by Chaoyuuu

Solved #177 

![image](https://user-images.githubusercontent.com/41495987/134046265-8d68b987-cd1b-4248-95f1-f90d326d5e03.png)

2021-09-23 07:57 UTC, Johnny850807 approved these changes
LGTM

2021-09-24 07:50 UTC, Wally5077 requested changes
Review done

2021-09-24 07:50 UTC, Wally5077 commented on src/app/problem/Model.js
> +        this.compilationScript = script
```;```

2021-09-24 07:50 UTC, Wally5077 commented on src/app/problem/editor/right/CompilationScript.js
> +        languageEnv.updateCompilationScript(script)
```;```

2021-09-24 07:50 UTC, Wally5077 commented on src/app/problem/editor/right/CompilationScript.js
> +        setScript(scriptBackUp)
```;```

2021-09-24 08:13 UTC, Wally5077 approved these changes
LGTM

2021-09-24 08:13 UTC, merged