Dev/207 Tags API integrate
Judge-Girl/Judge-Girl-CMS pull request #208
Opened 2021-09-20 17:48 UTC by Chaoyuuu

Solved #207

2021-09-22 07:04 UTC, Wally5077 requested changes
Review done

2021-09-22 07:04 UTC, Wally5077 commented on src/app/problem/editor/right/Tags.js
> +                    setTextItems(p.tags.map(tag => new TextItem(tag)))
```;```

2021-09-22 17:24 UTC, Chaoyuuu commented
Hi, I have changed the CSS. Please review again. Thanks! 😄

2021-09-23 07:09 UTC, Wally5077 approved these changes
LGTM

2021-09-23 07:09 UTC, Wally5077 commented on src/app/problem/ProblemList.js
> +                                      <div>Tags</div>
NIT: Why did you use ```div``` here?

2021-09-23 07:11 UTC, Johnny850807 approved these changes
LGTM

2021-09-23 16:30 UTC, merged