Dev/197 Actions in the New Problem Editor
Judge-Girl/Judge-Girl-CMS pull request #216
Opened 2021-09-25 10:51 UTC by Chaoyuuu

Closed #179 

![image](https://user-images.githubusercontent.com/41495987/134768823-b076c0f6-2e27-4def-b886-37fdf7b5b940.png)

![image](https://user-images.githubusercontent.com/41495987/134768854-a0cb7225-f242-42b2-805e-a1abcf0dbcc5.png)

2021-09-25 16:54 UTC, Johnny850807 requested changes
Review done

2021-09-25 16:54 UTC, Johnny850807 commented on src/app/problem/editor/right/Actions.js
> +                    setArchived(p.archived)
semicolon

2021-09-26 09:14 UTC, Wally5077 approved these changes
LGTM

2021-09-26 11:11 UTC, Johnny850807 approved these changes
LGTM

2021-09-26 11:11 UTC, merged