Dev/202: TestcaseIOsPatching
Judge-Girl/Judge-Girl-CMS pull request #220
Opened 2021-09-27 11:45 UTC by Johnny850807

resolve: #202

2021-09-28 07:07 UTC, Wally5077 requested changes
review done

2021-09-28 07:44 UTC, Johnny850807 commented on src/app/problem/editor/right/testcases/TestcaseEditor.js
> +                })} fileRemovable={fileRemovable} removeItem={item => removeFile(item.text)}
It cannot be achieved. 

The first pair of braces will be seen as the wrapper of multi-line statements within the lambda.

2021-09-28 07:45 UTC, Johnny850807 commented on src/app/problem/editor/right/testcases/TestcaseEditor.js
> +                })} fileRemovable={fileRemovable} removeItem={item => removeFile(item.text)}
s

2021-09-28 07:46 UTC, Johnny850807 commented
asdas

2021-09-28 07:49 UTC, Wally5077 commented on src/app/problem/editor/right/testcases/TestcaseEditor.js
> +                })} fileRemovable={fileRemovable} removeItem={item => removeFile(item.text)}
ok

2021-09-28 07:49 UTC, Wally5077 approved these changes
LGTM

2021-09-30 07:54 UTC, Chaoyuuu approved these changes
LGTM

2021-10-04 10:15 UTC, merged