Dev/130 [ExamQuestion] Question order jumping number
Judge-Girl/Judge-Girl-CMS pull request #223
Opened 2021-09-29 14:22 UTC by Wally5077

**before fix:**
<img src='https://user-images.githubusercontent.com/26381900/135287691-6f864b9e-38f9-450b-9a55-a3929842a9ea.png' width='1000'/>

---

**after fix:**
<img src='https://user-images.githubusercontent.com/26381900/135287787-70aa43b7-6631-411d-b3cb-cf834430e4b3.png' width='1000'/>

2021-09-30 08:18 UTC, Chaoyuuu requested changes
Review Done!

2021-09-30 08:18 UTC, Chaoyuuu commented on src/app/exam/questions/ExamQuestions.js
> +                            <FakeLink>{`${question.problemId} ${question.problemTitle}`}</FakeLink>,
Can you change this to the real link?
When clicking the questions, it should redirect to the related problem editor.

2021-09-30 08:18 UTC, Chaoyuuu commented on src/app/exam/questions/ExamQuestions.js
> +                                          }}>
Can you move this style into `.scss`?  
And please update the backgroundColor to `#FFC700`.

2021-09-30 08:38 UTC, Chaoyuuu commented
Hey, here are some comments. 
- I think this is a duplicate code. We have the same style in the `examQuestions.scss`. 
![image](https://user-images.githubusercontent.com/41495987/135415995-5d9964e1-aba4-4e1e-9fa5-3f51c47a3c46.png)

- Does `color:#FFF` really work? Please fix it. Thanks.
<img src="https://user-images.githubusercontent.com/41495987/135417458-5c7c5541-0f12-4dc9-ae01-c3cb0458e4e4.png" width="300px"/>

2021-10-01 07:33 UTC, Johnny850807 requested changes
Review done

2021-10-01 07:33 UTC, Johnny850807 commented on src/app/exam/questions/ExamQuestions.js
> +                     style={{alignSelf: "flex-end", position: "relative"}}>
write it into the scss file

2021-10-05 01:14 UTC, Chaoyuuu requested changes
Review done

2021-10-05 01:14 UTC, Chaoyuuu commented on src/app/exam/questions/ExamQuestions.scss
>        color: #FFF;
please remove it if we don't need it.

2021-10-05 06:33 UTC, Johnny850807 approved these changes
ＬＧＴＭ

2021-10-05 14:19 UTC, Chaoyuuu approved these changes
LGTM

2021-10-05 14:22 UTC, merged