Dev/165 Average score should show "0" if there are not questions in the exam
Judge-Girl/Judge-Girl-CMS pull request #246
Opened 2021-12-08 17:04 UTC by snowmancc

resolve #165 

![image](https://user-images.githubusercontent.com/39298006/145251181-518a1076-c54b-46fd-95a0-a3f62b5d4d96.png)

![image](https://user-images.githubusercontent.com/39298006/145251238-89d0ea18-eec0-48d7-bba3-d0c87b04c170.png)

2021-12-09 02:00 UTC, Chaoyuuu approved these changes
LGTM! 😄

2021-12-09 05:11 UTC, Wally5077 requested changes
Review done

2021-12-09 05:11 UTC, Wally5077 commented on src/services/ExamTranscriptService.js
> -export {ExamTranscriptService};
Change it back.

2021-12-14 15:06 UTC, Wally5077 approved these changes
LGTM

2021-12-14 15:06 UTC, merged