Dev/52
Judge-Girl/Judge-Girl-CMS pull request #61
Opened 2021-04-29 05:42 UTC by chiyuyu

- issue: #52 
 - componentize MarkdownEditor component
 
<img width="1196" alt="截圖 2021-04-29 下午1 40 44" src="https://user-images.githubusercontent.com/42633015/116506756-81e7c680-a8f0-11eb-8d39-db0ea9abbfef.png">
<img width="579" alt="截圖 2021-04-29 下午1 40 59" src="https://user-images.githubusercontent.com/42633015/116506767-8c09c500-a8f0-11eb-9707-48511c7d2006.png">
<img width="812" alt="截圖 2021-04-29 下午1 41 17" src="https://user-images.githubusercontent.com/42633015/116506792-962bc380-a8f0-11eb-8727-f125f7c5d3f5.png">
<img width="810" alt="截圖 2021-04-29 下午1 41 46" src="https://user-images.githubusercontent.com/42633015/116506828-a643a300-a8f0-11eb-86ca-5d2e795d7f75.png">

2021-04-29 06:53 UTC, Chaoyuuu requested changes
Review Done :)

2021-04-29 06:53 UTC, Chaoyuuu commented on src/app/problem/edit/ProblemEditorTitle.css
> +    font-size: 35px;
use `scss` !!!

2021-04-29 06:53 UTC, Chaoyuuu commented on src/app/problem/edit/description/MarkdownEditor.js
> +        }
Add `//TODO: empty information`.

2021-04-29 06:53 UTC, Chaoyuuu commented on src/app/problem/edit/description/MarkdownEditor.js
> +    const [textareaVal, setTextareaVal] = useState('Press Edit Description to start writing the description. :smile: Styling with Markdown is supported. :+1:\n');
remove `:smile:` and `:+1:`. We can't support it now. 😢

2021-04-29 06:53 UTC, Chaoyuuu commented on src/services/ProblemEditorService.js
> +
rename `ProblemEditorService` to `ProblemService`.

2021-04-29 06:53 UTC, Chaoyuuu commented on src/services/ProblemEditorService.js
> +            timeout: 10000
Change baseURL to `process.env.REACT_APP_PROBLEM_SVC_BASE_URL`.
And add `REACT_APP_PROBLEM_SVC_BASE_URL=http://api.judgegirl.beta.pdlab.csie.ntu.edu.tw` in `.env` file.

2021-04-29 06:53 UTC, Chaoyuuu commented on src/app/problem/edit/description/MarkdownEditor.js
> +    const [editingState, setEditingState] = useState(false);
Move `MarkdownEditor` to app/commons.

2021-04-29 06:53 UTC, Chaoyuuu commented on src/app/problem/edit/description/MarkdownEditor.js
> +import React, {useState} from "react";
Where did you use `ProblemEditor.css` ?
Don't use `ProblemEditor.css` when `MarkdownEditor` is a common component.

2021-04-29 06:53 UTC, Chaoyuuu commented on src/app/problem/edit/description/MarkdownEditor.js
> +                    >
formate code.

2021-04-29 06:53 UTC, Chaoyuuu commented on src/app/problem/edit/description/Description.js
> +        </div>
move it to `ProblemEditor`.

2021-04-29 06:53 UTC, Chaoyuuu commented on src/app/problem/edit/ProblemEditorTitle.js
> +        }
Add `//TODO: empty info`

2021-04-29 06:53 UTC, Chaoyuuu commented on src/app/problem/edit/ProblemEditorTitle.js
> +                            setProblemNameInput(lastProblemNameInput);
remove comment.

2021-04-30 05:07 UTC, Chaoyuuu requested changes
Review Done !

2021-04-30 05:07 UTC, Chaoyuuu commented on src/app/commons/MarkdwonEditor.scss
> +    width: 756px;
remember to extract common CSS !!
e.g., `background: #FFFFFF`, `display: block`, `box-sizing: border-box`, etc.

2021-05-01 12:58 UTC, Chaoyuuu requested changes
Last things to change 👍🏻

2021-05-01 12:58 UTC, Chaoyuuu commented on src/app/commons/MarkdwonEditor.scss
> +      cursor: pointer;
remove comment :)

2021-05-01 12:58 UTC, Chaoyuuu commented on src/app/commons/MarkdwonEditor.scss
> +      cursor: pointer;
ditto

2021-05-01 12:58 UTC, Chaoyuuu commented on src/services/ProblemService.js
> +    }
redundant, remove this.

remember to invoke `.then()` on the client-side

2021-05-01 12:58 UTC, Chaoyuuu commented on src/services/ProblemService.js
> +    }
ditto

2021-05-01 12:58 UTC, Chaoyuuu commented on src/app/commons/MarkdwonEditor.scss
> +  display: block;
use variable.
```css
$markdown-background-color: #FFFFFF;

.MarkdownEditor {
  background: $markdown-background-color;
  display: block;
  ...
}

2021-05-01 12:58 UTC, Chaoyuuu commented on src/app/commons/MarkdwonEditor.scss
> +      border: 1px solid #C6C4C4;
`background: $markdown-background-color;`

2021-05-03 06:12 UTC, Chaoyuuu approved these changes
LGTM

2021-05-03 06:43 UTC, Johnny850807 requested changes
Review done

2021-05-03 06:43 UTC, Johnny850807 commented on src/app/commons/MarkdwonEditor.scss
> +.MarkdownEditor {
rename to `markdown-editor`

2021-05-03 06:43 UTC, Johnny850807 commented on src/app/problem/edit/ProblemEditorTitle.js
> +        if (problemNameInput === '') {
`problemNameInput.isEmpty()`

2021-05-03 06:43 UTC, Johnny850807 commented on src/app/problem/edit/ProblemEditorTitle.js
> +            .then();
`.then(() => console.log('The problem's title has been modified'))`

2021-05-05 02:51 UTC, Johnny850807 approved these changes
ＬＧＴＭ

2021-05-05 09:22 UTC, merged