Dev/55 Rejudge
Judge-Girl/Judge-Girl-CMS pull request #71
Opened 2021-05-07 23:42 UTC by nyngwang

![image](https://user-images.githubusercontent.com/24765272/117518009-bcc4bb00-afd0-11eb-9b78-d591f3baa38d.png)
![image](https://user-images.githubusercontent.com/24765272/117518021-cc440400-afd0-11eb-882f-5b85bbb504ec.png)
![image](https://user-images.githubusercontent.com/24765272/117518028-d239e500-afd0-11eb-836d-7b68d964149f.png)

2021-05-13 02:21 UTC, Johnny850807 commented
Happy Birthday!

2021-05-13 02:34 UTC, timt1028 commented
╬╔╦╦═╦═╦═╦╦╗╔═╦╦═╦══╦╦╦═╦═╦╦╗╬
╬║╩║╬║╬║╬║║║║╚║║╬╠╗╔╣╩║║║╬║║║╬
╬║╦║║║╔╣╔╬╗║║╔║║═╣║║║╦║║║║╠╗║╬
╬╚╩╩╩╩╝╚╝╚═╝╚═╩╩╩╝╚╝╚╩╩═╩╩╩═╝╬

2021-05-13 02:55 UTC, snowmancc commented
╬╔╦╦═╦═╦═╦╦╗╔═╦╦═╦══╦╦╦═╦═╦╦╗╬
╬║╩║╬║╬║╬║║║║╚║║╬╠╗╔╣╩║║║╬║║║╬
╬║╦║║║╔╣╔╬╗║║╔║║═╣║║║╦║║║║╠╗║╬
╬╚╩╩╩╩╝╚╝╚═╝╚═╩╩╩╝╚╝╚╩╩═╩╩╩═╝╬

2021-05-13 03:05 UTC, timt1028 approved these changes

2021-05-13 03:09 UTC, Chaoyuuu commented
![image](https://user-images.githubusercontent.com/41495987/118072065-b0c76780-b3db-11eb-8f8a-cedfaf659e88.png)

2021-05-13 03:19 UTC, haribo0915 commented
╬╔╦╦═╦═╦═╦╦╗╔═╦╦═╦══╦╦╦═╦═╦╦╗╬
╬║╩║╬║╬║╬║║║║╚║║╬╠╗╔╣╩║║║╬║║║╬
╬║╦║║║╔╣╔╬╗║║╔║║═╣║║║╦║║║║╠╗║╬
╬╚╩╩╩╩╝╚╝╚═╝╚═╩╩╩╝╚╝╚╩╩═╩╩╩═╝╬
@Johnny850807 應該給壽星 @nyngwang 多幾個 issue 當生日禮物

2021-05-13 03:21 UTC, Johnny850807 reviewed
> ╬╔╦╦═╦═╦═╦╦╗╔═╦╦═╦══╦╦╦═╦═╦╦╗╬
> ╬║╩║╬║╬║╬║║║║╚║║╬╠╗╔╣╩║║║╬║║║╬
> ╬║╦║║║╔╣╔╬╗║║╔║║═╣║║║╦║║║║╠╗║╬
> ╬╚╩╩╩╩╝╚╝╚═╝╚═╩╩╩╝╚╝╚╩╩═╩╩╩═╝╬
> @Johnny850807 應該給壽星 @nyngwang 多幾個 issue 當生日禮物

2021-05-13 03:41 UTC, loag20056 commented
╬╔╦╦═╦═╦═╦╦╗╔═╦╦═╦══╦╦╦═╦═╦╦╗╬
╬║╩║╬║╬║╬║║║║╚║║╬╠╗╔╣╩║║║╬║║║╬
╬║╦║║║╔╣╔╬╗║║╔║║═╣║║║╦║║║║╠╗║╬
╬╚╩╩╩╩╝╚╝╚═╝╚═╩╩╩╝╚╝╚╩╩═╩╩╩═╝╬

建中王甯我老大 生日快樂歐

2021-05-13 04:09 UTC, zseqw123 commented
╬╔╦╦═╦═╦═╦╦╗╔═╦╦═╦══╦╦╦═╦═╦╦╗╬
╬║╩║╬║╬║╬║║║║╚║║╬╠╗╔╣╩║║║╬║║║╬
╬║╦║║║╔╣╔╬╗║║╔║║═╣║║║╦║║║║╠╗║╬
╬╚╩╩╩╩╝╚╝╚═╝╚═╩╩╩╝╚╝╚╩╩═╩╩╩═╝╬

2021-05-13 04:15 UTC, timt1028 commented on .idea/workspace.xml
> +<<<<<<< HEAD
WTF

2021-05-13 04:25 UTC, Wally5077 commented
╬╔╦╦═╦═╦═╦╦╗╔═╦╦═╦══╦╦╦═╦═╦╦╗╬
╬║╩║╬║╬║╬║║║║╚║║╬╠╗╔╣╩║║║╬║║║╬
╬║╦║║║╔╣╔╬╗║║╔║║═╣║║║╦║║║║╠╗║╬
╬╚╩╩╩╩╝╚╝╚═╝╚═╩╩╩╝╚╝╚╩╩═╩╩╩═╝╬
你大寧哥，生日快樂啦

2021-05-13 04:57 UTC, ntuhan commented
生日快樂甯哥 什麼時候要下去ㄋ

2021-05-13 05:56 UTC, b4735268 commented
╬╔╦╦═╦═╦═╦╦╗╔═╦╦═╦══╦╦╦═╦═╦╦╗╬
╬║╩║╬║╬║╬║║║║╚║║╬╠╗╔╣╩║║║╬║║║╬
╬║╦║║║╔╣╔╬╗║║╔║║═╣║║║╦║║║║╠╗║╬
╬╚╩╩╩╩╝╚╝╚═╝╚═╩╩╩╝╚╝╚╩╩═╩╩╩═╝╬
老大，約甲奔阿

2021-05-13 06:27 UTC, nyngwang commented on .idea/workspace.xml
> +<<<<<<< HEAD
笑死 我自己都不知道有這個

2021-05-13 13:47 UTC, Johnny850807 requested changes
Review done.

2021-05-13 13:47 UTC, Johnny850807 commented on src/app/exam/problems/ExamProblems.scss
> +      //line-height: 30px;
remove this

2021-05-13 13:47 UTC, Johnny850807 commented on src/services/SubmissionService.js
> +    async submit(problem) {
Should be renamed to `rejudge`

and don't implement this method at this moment, the issue created for this #76

2021-05-13 13:47 UTC, Johnny850807 commented on src/services/ExamService.js
> +    async deleteExamProblem(problem) {
` async deleteExamProblem(question) {`

2021-05-13 13:47 UTC, Johnny850807 commented on src/app/exam/problems/ExamProblems.js
> +            studentId: "r09900000"
no, don't hard-code

2021-05-13 13:47 UTC, Johnny850807 commented on src/services/SubmissionService.js
> +        const {problemId, langEnvName, studentId} = problem
wtf is this? `const {problemId, langEnvName, studentId} = problem`

please don't rush on the code.
Ask @snowmancc for the api details (rejudge)

2021-05-13 13:47 UTC, Johnny850807 commented on src/app/exam/problems/ExamProblems.js
> +                    .then(res => setProblemId2Title(prev => prev.set(problem.problemId, res.title)))
don't name anything with `2`

2021-05-13 13:47 UTC, Johnny850807 commented on src/app/exam/problems/ExamProblems.js
> +            })
don't iterate on every problem

the get exam overview api has already included the problem's title

2021-05-14 08:48 UTC, Johnny850807 requested changes
Review done

2021-05-14 08:48 UTC, Johnny850807 commented on src/app/exam/problems/ExamProblems.scss
> +      //line-height: 30px;
@nyngwang unresolved

2021-05-14 08:48 UTC, Johnny850807 commented on src/app/exam/problems/ExamProblems.js
> +    const editProblem = (problemId) => {
rename `editProblem` to `editQuestion`

2021-05-14 08:48 UTC, Johnny850807 commented on src/app/exam/problems/ExamProblems.js
> +        }, 5000)
why is the need for `setTimeout`? 

do this in the "then" section 

and what does `0` mean?

2021-05-14 08:48 UTC, Johnny850807 commented on src/app/exam/problems/ExamProblems.js
> +            }).then(res => console.log("deleted", res))
give a more clearer comment, this is unclear when we debug from a ton of logs

2021-05-14 08:48 UTC, Johnny850807 commented on src/app/exam/problems/ExamProblems.js
> +    const [rejudgeProblemId, setRejudgeProblemId] = useState(0)
what does `0` mean?

Declare a constant to describe it.
More usually, it should be`-1`?

2021-05-14 08:48 UTC, Johnny850807 commented on src/app/exam/problems/ExamProblems.js
> +    const [examProblems, setExamProblems] = useState(null);
Don't understand, why all exams are passed in.

Just pass the current exam in.

2021-05-14 15:12 UTC, Johnny850807 requested changes
Review done

2021-05-14 15:12 UTC, Johnny850807 commented on src/app/exam/problems/ExamQuestions.js
> +    }
`questionId` -> `problemId`

**question's id = (examId, problemId)**

2021-05-14 15:12 UTC, Johnny850807 commented on src/app/commons/IndexBanner/InPageNavigationBar.js
> +    const { firstParamResetState } = events
add refactor TODO

2021-05-14 15:38 UTC, Johnny850807 approved these changes
ＬＧＴＭ

2021-05-14 15:42 UTC, merged